environment:
  BACKUP_WEBHOOK_URL: https://openunited.com/backup/start/
  BACKUP_WEBHOOK_KEY: "${BACKUP_WEBHOOK_KEY}"
packages:
    - name: openunited-platform
      shared: false
      functions:
        - name: trigger-backup
          runtime: python:3.11
          web: false
          triggers:
          - name: trigger-backup
            sourceType: scheduler
            sourceDetails:
              cron: "5 4 * * *"
