name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag registry.digitalocean.com/openunited/core:$(date +%s) --tag registry.digitalocean.com/openunited/core:latest
    - name: Login to registry
      shell: bash
      run: doctl registry login --expiry-seconds 600
    - name: Push to DigitalOcean
      run: docker push -a registry.digitalocean.com/openunited/core
    
