name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - uses: actions/checkout@v3
    - name: Update the project version
      run: pip install python-semantic-release && python -m semantic_release version
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Build the Docker image
      run: |
        export VERSION=$(python -c 'import version; print(version.version)')
        docker build . --file Dockerfile --tag registry.digitalocean.com/openunited/core:$VERSION
    - name: Login to registry
      run: doctl registry login --expiry-seconds 600
    - name: Push to DigitalOcean
      run: docker push -a registry.digitalocean.com/openunited/core
    - name: Fetch current spec file
      run: doctl --context openunited apps spec get 0fe572eb-1984-47e3-aabd-d1056b014486 > spec.yaml
    - name: Update image tag
      run: |
        export VERSION=$(python -c 'import version; print(version.version)')
        sed -i "s/\(.*tag: \).*/\1$VERSION/" spec.yaml
    - name: Update the environment
      run: doctl --context openunited apps update 0fe572eb-1984-47e3-aabd-d1056b014486 --spec spec.yaml
