name: Runs Tests

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - run: python manage.py test
      env:
        DJANGO_SETTINGS_MODULE: openunited.settings.development
        DJANGO_SECRET_KEY: 123456789
