name: Runs Tests

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: python manage.py test
      env:
        DJANGO_SETTINGS_MODULE: openunited.settings.development
        DJANGO_SECRET_KEY: 123456789
